library(readr)
library(dplyr)
library(lubridate)
library(reshape)
library(reshape2)
library(tidyr)
library(tidyverse)
library(bizdays)
library(timeDate)
library(ggplot2)
library(plotly)
library(timeSeries)
library(fpp2)
library(forecast)
library(tseries)
library(MASS)
library(xts)
library(data.table)
library(tsibble)
library(ggfortify)
library(fable)
library(zoo)
library(bizdays)
library(ggeasy)
library(harrypotter)
library(bizdays)
library(timeDate)
library(astsa)
library(Metrics)
library(quantmod)
library(tseries)
library(TSstudio)
library(DMwR2)
library(rminer)
library(WDI)
library(RJSONIO)
df <- read.csv("C:/Users/user/Desktop/NIFTY_WEEKLY.csv")
head(df)
str(df)
summary(df)
class(df)
df$Date<-as.Date(df$Date,format = "%d-%m-%Y")
plot(df)
data<- ts(df$Close, start =c(2017,03,27), end=c(2022,03,28),frequency= 52)
plot(data)
adf.test(data)
Pacf(data,lag.max = 20)
Acf(data,lag.max=20)
train_model_1<- diff(data,difference=1,)
train_model_1
plot(train_model_1)
adf.test(train_model_1)
Pacf(train_model_1,lag.max = 20)
Acf(train_model_1,lag.max=20)
str(train_model_1)
ts_info(train_model_1)
ts_plot(train_model_1)

train_series = ts(data[1:209], start =c(2017,03,27), end=c(2021,03,22),frequency= 52)
head(train_series)

tail(train_series)
plot(train_series)
test_series = ts(df$Close[210:262], start =c(2021,03,29), end=c(2022,03,28),frequency= 52)
head(test_series)
df$Close[210]
tail(test_series)
tail(df)
plot(test_series)
str(train_series)

##Forecasting Arima Model##

arimaModel=arima(train_series, order=c(6,1,6))
print(arimaModel)
forecast=predict(arimaModel, 52)
str(forecast)
plot(forecast$pred)
ts_info(forecast$pred)
plot(forecast(arimaModel, h = 52))
mmetric(test_series, forecast$pred, c("MAE","RMSE","MSE","MAPE"))


arimaModel=arima(data, order=c(6,1,6))
print(arimaModel)
forecast=predict(arimaModel, 52)
str(forecast)
plot(forecast$pred)
ts_info(forecast$pred)
plot(forecast(arimaModel, h = 52))

    




